### ISSUE TITLE
[feature request] Add type of change

### ISSUE THREAD

**Issue by mwerle** [BenjaminCronin/KerbalChangelog#13]
Changelogs should be able to distinguish between several different types of changes:

- changes (as you support now)
- fixes (changes, but specifically to fix a known bug)
- new (new features)
- deprecated/removed (for things which have been removed)

Unfortunately 1.2.0.0 already added the "subchange" tag, or I would have proposed having a "sub"/"indent"/"level" parameter on each change as well as the "type".

Or in addition to "change" have "new" and "fix".

So not entirely sure how to integrate without breaking existing KerbalChangelog-compatible changelogs.

PS: This seems to be a decent "best practices" for Changelogs: https://keepachangelog.com/

Might also be a useful reference for KerbalChangelogCreator?

**Comment by AmberCronin** [comment]
Again, sorry for not seeing this until now, GitHub was wonky and didn't alert me. 
Thank you for the link, I'll be sure to give that a read! I actually forgot about Kerbal Changelog Creator, so that'll most likely be useful for that as well :P
In terms of KCL itself: Would this group changes/additions/fixes under different categories for each version? As of now, all changes are denoted either by an astrisk (`*`) for major changes, or a dash (`-`) for minor changes. I can handle the integration if I know exactly what needs to be changed cosmetically.

**Comment by mwerle** [comment]
KACL recommends grouping change types together - there are examples on the page.

But you don't have to adhere strictly to their recommendations; do whatever works for this mod :)

**Comment by AmberCronin** [comment]
So I see two ways of doing this (which I'll show below, at the VERSION node level)
```
version = 1.3.0
ADD
{
    change = Add features suggested by mwerle
    note = Add 'visit website' button
    note = Add different change-type nodes
}
FIX
{
    change = Fix pizza oven
}
DEP
{
    change = Depreciate hot dogs
}
```

Or I could do something like
```
version = 1.3.0
CHANGE
{
    type = Add
    change = Add features suggested by mwerle
...
}
CHANGE
{
    type = Fix
    change = ...
}
```

Would you prefer one rather than another? The real work comes with how to display them, and that's easy enough. Everything else is just copy-pasting code and changing some names.

**Comment by AmberCronin** [comment]
Thinking about it, having a `type` field is probably the way to go. I think I'll try to get that implemented tonight or tomorrow.
Cheers

**Comment by AmberCronin** [comment]
Added with commit 595b9cd

**Comment by mwerle** [comment]
Sorry I didn't reply earlier. But adding the "type" field is, I think, the better way to go.
